# Generated by Django 5.1.6 on 2025-02-20 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offerte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('aantal_personen', models.PositiveIntegerField()),
                ('straat', models.CharField(max_length=255)),
                ('nummer', models.CharField(max_length=50)),
                ('gemeente', models.CharField(max_length=255)),
                ('gewenste_datum', models.DateField()),
                ('gewenste_tijd', models.TimeField()),
                ('formule', models.CharField(max_length=50)),
                ('extra_info', models.TextField(blank=True, null=True)),
                ('afstand', models.FloatField()),
                ('extra_kosten', models.DecimalField(decimal_places=2, max_digits=10)),
                ('basis_prijs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('totaal_prijs', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
