# Generated by Django 5.1.6 on 2025-02-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrosnacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerte',
            name='btw_nummer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='offerte',
            name='korting',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
