# Generated by Django 5.1.6 on 2025-02-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrosnacks', '0002_offerte_btw_nummer_offerte_korting'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerte',
            name='event_adres',
            field=models.CharField(default='Onbekend', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offerte',
            name='is_bevestigd',
            field=models.BooleanField(default=False),
        ),
    ]
