# Generated by Django 5.1.6 on 2025-02-23 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrosnacks', '0003_offerte_event_adres_offerte_is_bevestigd'),
    ]

    operations = [
        migrations.AddField(
            model_name='offerte',
            name='telefoon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
