# Generated by Django 5.1.6 on 2025-02-23 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrosnacks', '0004_offerte_telefoon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerte',
            name='telefoon',
            field=models.CharField(default='onbekend', max_length=20),
            preserve_default=False,
        ),
    ]
