# Generated by Django 5.1.6 on 2025-03-26 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrosnacks', '0006_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offerte',
            old_name='naam',
            new_name='naam_bedrijf',
        ),
        migrations.AddField(
            model_name='offerte',
            name='naam_contactpersoon',
            field=models.CharField(default='Onbekende contactpersoon', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offerte',
            name='is_bevestigd',
            field=models.CharField(default='Nieuwe offerte', max_length=50),
        ),
    ]
