# Generated by Django 5.1.6 on 2025-04-24 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrosnacks', '0007_rename_naam_offerte_naam_bedrijf_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Klant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naam_contactpersoon', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('straat', models.CharField(max_length=255)),
                ('nummer', models.CharField(max_length=50)),
                ('gemeente', models.CharField(max_length=255)),
                ('telefoon', models.CharField(max_length=20)),
                ('naam_bedrijf', models.CharField(max_length=255)),
                ('btw_nummer', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
