# Generated by Django 5.1.6 on 2025-05-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrosnacks', '0010_actievanhetmoment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actievanhetmoment',
            name='titel',
            field=models.CharField(max_length=100),
        ),
    ]
