# Generated by Django 5.1.6 on 2025-05-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrosnacks', '0011_alter_actievanhetmoment_titel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=200)),
                ('beschrijving', models.TextField()),
                ('loopt_tot', models.DateField()),
                ('aangemaakt_op', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ActieVanHetMoment',
        ),
    ]
