"""
Django settings for bakapp project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os
from decouple import config

load_dotenv()

EENVOUDIGFACTUREREN_EMAIL = config('EENVOUDIGFACTUREREN_EMAIL')
EENVOUDIGFACTUREREN_PASSWORD = config('EENVOUDIGFACTUREREN_PASSWORD')
OPENROUTE_API_KEY = os.getenv('OPENROUTE_API_KEY')

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'dashboard'
# Veiligheidsinstellingen voor HTTP (lokale ontwikkeling)
CSRF_COOKIE_HTTPONLY = False  # Vereist voor AJAX/JS om de token te lezen
SESSION_COOKIE_HTTPONLY = True  # Aanbevolen voor sessiebeveiliging
CSRF_COOKIE_SECURE = False  # Uitgeschakeld voor HTTP
SESSION_COOKIE_SECURE = False  # Uitgeschakeld voor HTTP
CSRF_COOKIE_SAMESITE = 'Lax'  # Goede balans tussen veiligheid en functionaliteit
SESSION_COOKIE_SAMESITE = 'Lax'

# Vertrouwde origings voor CSRF (alleen HTTP voor ontwikkeling)
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://13.60.12.35:8000',
    'https://13.60.12.35:8000',
    'http://127.0.0.1:8000',
    # os.getenv('AWS_PUBLIC_IP', ''),    or     Replace with your actual AWS public IP


    #'http://retrosnacks.be',  # Alleen als je dit lokaal test
    #'http://www.retrosnacks.be'  # Alleen als je dit lokaal test
]

# HTTPS-instellingen UITGESCHAKELD voor lokale ontwikkeling
SECURE_PROXY_SSL_HEADER = None
SECURE_SSL_REDIRECT = False  # Geen redirect naar HTTPS
SECURE_HSTS_SECONDS = 0  # HSTS uitgeschakeld
SECURE_HSTS_INCLUDE_SUBDOMAINS = False
SECURE_HSTS_PRELOAD = False


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*sa0oy6g#0^frf5vjv_lq0rqw4dx!3481%ymeg7r8!ow520!&b'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'retrosnacks',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

ROOT_URLCONF = 'bakapp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Voeg de templates-map toe
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bakapp.wsgi.application'

CORS_ALLOW_ALL_ORIGINS = True  # Zet dit op True voor tests, later beperken

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

load_dotenv()

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME'),
        'USER': os.getenv('DB_USER'),
        'PASSWORD': os.getenv('DB_PASSWORD'),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]

STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media bestanden (uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

load_dotenv()
# mail contactform 
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
